global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: node
    static_configs:
      - targets:
          - 192.168.0.19:9100
        labels:
          instance: raspi

  - job_name: switchbot
    scrape_interval: 5m
    static_configs:
      - targets:
          - switchbot_exporter:8000
        labels:
          instance: switchbot
